name: Docker TCA – build & upload OCI bundle

description: >
  Builds the container image **offline** (type=oci), uploads it with
  secure-upload-folder, and writes a provenance layout.

inputs:
  dockerfile:
    required: true
  context:
    required: false
    default: "."
  build-args:
    required: false
  image-tag:
    required: true

outputs:
  oci-download-name:
    value: ${{ steps.build.outputs.artifact-name }}
  oci-download-sha256:
    value: ${{ steps.build.outputs.artifact-sha256 }}

runs:
  using: composite
  steps:
    - id: build
      name: Build OCI (no push)
      uses: ./.github/actions/docker-build-only
      with:
        dockerfile: ${{ inputs.dockerfile }}
        docker-context: ${{ inputs.context }}
        build-args: ${{ inputs.build-args }}

    - name: Write provenance layout
      shell: bash
      run: |
        mkdir -p .slsa
        cat > .slsa/layout.json <<EOF
        {
          "version": 1,
          "attestations": [
            {
              "name": "${{ inputs.image-tag }}",
              "subjects": [
                {
                  "name": "ghcr.io/${{ github.repository_owner }}/$(basename ${{ github.repository }}):${{ inputs.image-tag }}",
                  "digest": { "sha256": "${{ steps.build.outputs.digest }}" }
                }
              ]
            }
          ]
        }
        EOF
