name: Build and push docker containers to ghcr.io
description: |
  This action will ensure the image name is lowercased and that any artifacts are available.

inputs:
  dockerfile:
    description: The path of the Dockerfile to build
    required: true
  image-name:
    description: "The full image name excluding ghcr.io/<my_container>"
    required: true
  image-tag:
    description: "The image tag"
    required: true
  docker-context:
    description: The path for the docker build context, defaults to '.'
    required: false
    default: .
  dry-run:
    description: Perform all actions but without committing changes
    required: false
    default: "false"
  build-args:
    description: List of build-time variables
    required: false

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      name: Download available artifacts # this supports use of artifacts (currently only frontends)
      with:
        path: artifacts/

    - name: Resolve container image name
      shell: bash
      run: |
        FULL="ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}"
        echo "LOWERCASED=$(echo "$FULL" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"
        
    - name: Install Cosign
      uses: sigstore/cosign-installer@3454372f43399081ed03b604cb2d021dabca52bb # v3.8.2
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

    - name: Log in to the Container registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
        ecr: false

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: ${{ inputs.docker-context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.dry-run != 'true' }}
        pull: true
        tags: ${{ env.LOWERCASED }}:${{ inputs.image-tag }}
        build-args: ${{ inputs.build-args }}
        provenance: mode=max
        sbom: false

    - name: Sign the image with GitHub OIDC Token
      shell: bash
      env:
        DIGEST: ${{ steps.build.outputs.digest }}
        IMAGE_TAG: ${{ env.LOWERCASED }}:${{ inputs.image-tag }}
      run: |
        if [ -z "$DIGEST" ]; then
          echo "❌ Digest is empty. Build step may have failed." >&2
          exit 1
        fi

        echo "🔐 Signing $IMAGE_TAG@$DIGEST"
        cosign sign --yes $IMAGE_TAG@$DIGEST
