# ./.github/actions/docker-build-and-push/action.yml
name: Build and push docker containers to ghcr.io
description: |
  Build a Docker image (+ SBOM, provenance), tag it, and push.

inputs:
  dockerfile:
    description: Path to Dockerfile
    required: true
  image-name:
    description: repo part (e.g. `foo-api`)
    required: true
  image-tag:
    description: tag (e.g. `main`, `abc123`)
    required: true
  docker-context:
    description: build context
    required: false
    default: .
  dry-run:
    description: skip push
    required: false
    default: "false"
  build-args:
    description: build-arg list
    required: false
outputs:
  image:
    description: The full image name (including registry)
    value: ${{ env.IMAGE_REGISTRY }}/${{ inputs.image-name }}
  digest:
    description: The image digest produced by buildx
    value: ${{ steps.buildx.outputs.digest }}

runs:
  using: composite
  steps:
    - name: Log in to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Extract metadata (tags & labels)
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}

    - name: Build & push via Buildx
      uses: docker/build-push-action@v6
      id: buildx
      with:
        context:       ${{ inputs.docker-context }}
        file:          ${{ inputs.dockerfile }}
        push:          ${{ inputs.dry-run != 'true' }}
        pull:          true
        tags:          ${{ steps.meta.outputs.tags }}
        labels:        ${{ steps.meta.outputs.labels }}
        build-args:    ${{ inputs.build-args }}
        sbom:          true
        provenance:    mode=max
