name: Publish Docker image

inputs:
  artifact-name:
    required: true
    description: "artifact-name"
  artifact-sha256:
    required: true
    description: "artifact sha"
  image-tag:
    required: true
    description: "image-tag"

runs:
  using: composite
  steps:
    - name: Secure download bundle
      id: dload
      uses: slsa-framework/slsa-github-generator/actions/delegator/secure-download-folder@v2.1.0
      with:
        sha256: '${{ inputs.artifact-sha256 }}'
        name: '${{ inputs.artifact-name }}'

    - name: Log in to the Container registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
        ecr: false

    - name: Load & push
      shell: bash
      run: |
        docker image load -i "${{ steps.dload.outputs.folder }}/oci-image.tar"
        REF="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/${GITHUB_REPOSITORY##*/}:${{ inputs.image-tag }}"
        IMAGE_ID=$(docker images --format "{{.Repository}}:{{.Tag}}" | head -n1)
        docker tag "$IMAGE_ID" "$REF"
        docker push "$REF"
