name: Dotnet - Build
description: Build a dotnet project

inputs:
  solution:
    description: Is the path to a solution file.
    required: true

  project:
    description: Is the path to a project file.
    required: true

  dry-run:
    description: Perform all actions but without pushing the image
    required: false
    default: "false"

  sdk-version:
    description: Is a complete sdk version in format x.y.zzz
    required: false
    default: ""

  runtime-version:
    description: Is a complete runtime version in format x.y.z
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Load - global.json
      shell: bash
      run: |
        DIRECTORY=$(dirname '${{ inputs.solution }}')
        test -f "$DIRECTORY/global.json" || exit 0
        echo "DIRECTORY=$DIRECTORY" | tee -a $GITHUB_ENV
        echo "SDK=$(jq -rc '.sdk.version' "$DIRECTORY/global.json")" | tee -a $GITHUB_ENV
        echo "RUNTIME=$(jq -rc '.runtime.version' "$DIRECTORY/global.json")" | tee -a $GITHUB_ENV

    - name: Overwrite - if given optional input
      shell: bash
      run: |
        if [ ! -z "${{ inputs.sdk-version }}" ]; then
          echo "SDK=${{ inputs.sdk-version }}" | tee -a $GITHUB_ENV
        fi
        if [ ! -z "${{ inputs.runtime-version }}" ]; then
          echo "RUNTIME=${{ inputs.runtime-version }}" | tee -a $GITHUB_ENV
        fi

    - name: Resolve image name
      shell: bash
      run: echo "IMAGE_NAME=$(dirname '${{ inputs.solution }}')" >> $GITHUB_ENV

    - name: Resolve image tags
      uses: ./.github/actions/docker-tag-image-with-version
      
    - name: Fetch Dockerfile
      shell: bash
      run: cp ./Dockerfile.simplified ./Dockerfile

    - name: Build image
      uses: ./.github/actions/docker-build-and-push
      with:
        dockerfile: Dockerfile
        image-name: ${{ env.IMAGE_NAME }}
        image-tag: ${{ env.version }}
        docker-context: .
        dry-run: ${{ inputs.dry-run }}
        build-args: |
          PROJECT=${{ inputs.project }}
          SDK_VERSION=${{ env.SDK }}
          RUNTIME_VERSION=${{ env.RUNTIME }}

    - name: Scan image
      uses: ./.github/actions/docker-scan
      with:
        image-name:  ${{ env.IMAGE_NAME }}
        image-tag:   ${{ env.version }}
        upload-sarif: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
