name: "Secure attestations download"
description: "Download a set of attestations and verify SHA256"

inputs:
  name:
    description: "Artifact name (not the file path)"
    required: true
  path:
    description: "Path to download to"
    required: false
    default: "."
  sha256:
    required: true
    description: "Expected SHA256"

runs:
  using: "composite"
  steps:
    - uses: slsa-framework/slsa-github-generator/actions/delegator/secure-attestations-download@v1.8.0
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        sha256: ${{ inputs.sha256 }}
