name: Build Docker image (no push)

inputs:
  dockerfile:
    required: true
    description: "Dockerfile"
  docker-context:
    required: false
    default: '.'
    description: "Docker context"
  build-args:
    required: false
    description: "Build Args"

outputs:
  artifact-name:
    value: ${{ steps.prep.outputs.name }}
    description: "artifact name"
  artifact-sha256:
    value: ${{ steps.upload.outputs.sha256 }}
    description: "artifact digest"

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    - id: build
      name: Build OCI archive
      uses: docker/build-push-action@v6
      with:
        context:     ${{ inputs.docker-context }}
        file:        ${{ inputs.dockerfile }}
        push:        false
        outputs:     type=oci,dest=oci-image.tar
        build-args:  ${{ inputs.build-args }}

    - id: prep
      name: Make unique bundle name
      shell: bash
      run: |
        echo "name=oci-$(openssl rand -hex 16)-$RANDOM-$(date +%s)" >> "$GITHUB_OUTPUT"
        
    - name: Rename OCI archive to unique name
      shell: bash
      run: mv oci-image.tar "${{ steps.prep.outputs.name }}"

    - id: upload
      name: Secure upload folder
      uses: slsa-framework/slsa-github-generator/actions/delegator/secure-upload-folder@v2.1.0
      with:
        name: ${{ steps.prep.outputs.name }}
        path: ${{ steps.prep.outputs.name }}