name: Docker Builder – SLSA3 (hardened)

on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      context:
        required: false
        type: string
        default: "."
      build-args:
        required: false
        type: string
      image-tag:
        required: true
        type: string
      rekor-log-public:
        required: false
        type: boolean
        default: true
    secrets:
      github-token:
        required: true
    outputs:
      oci-download-name:
        value: ${{ jobs.run.outputs.oci-download-name }}
      oci-download-sha256:
        value: ${{ jobs.run.outputs.oci-download-sha256 }}

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
      actions: read
    outputs:
      slsa-token: ${{ steps.slsa-setup.outputs.slsa-token }}
    steps:
      - id: slsa-setup
        name: SLSA Setup
        uses: slsa-framework/slsa-github-generator/actions/delegator/setup-generic@v2.1.0
        with:
          slsa-workflow-recipient: "delegator_lowperms-generic_slsa3.yml"
          slsa-build-action-path: ".github/actions/docker-tca"
          slsa-runner-label: "ubuntu-latest"
          slsa-workflow-inputs: ${{ toJson(inputs) }}
          slsa-version: "v1.0"

  run:
    needs: setup
    uses: slsa-framework/slsa-github-generator/.github/workflows/delegator_lowperms-generic_slsa3.yml@v2.1.0
    permissions:
      contents: read
      id-token: write
      attestations: write
      actions: read
    with:
      slsa-token: ${{ needs.setup.outputs.slsa-token }}
    secrets:
      secret1: ${{ secrets.github-token }}
